<?php

namespace app\overrideModels;

use yii\web\Controller;

class ControllerOverride extends Controller {
    public function beforeAction($action)
    {
        \Yii::debug('dslkfjdskfjk');
        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }
}