<?php

namespace app\models\override;


use yii\web\ErrorAction;

class ErrorO extends ErrorAction {
    public function run()
    {
        if (\Yii::$app->getResponse()->setStatusCodeByException($this->exception)->statusCode == 404) {
            \Yii::debug('dfkldfkdl');
            return \Yii::$app->controller->redirect('/task/index');
        }

        return parent::run(); // TODO: Change the autogenerated stub
    }
}